### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by dzheltkov** [Vopreky/LU#1]
1) Реализовывать блочную версию через рекурсию -- не лучшая идея, можно вообще никогда не получить блок желаемого размера, да и код в итоге выглядит довольно странно и непонятно.
2) В Фортране лучше использовать двумерную индексацию для матриц, кроме того, лучше использовать не `do while`, а `do i = `. И в фортране нет блочной версии.
3) Версия с BLAS использует его только для бесполезной операции.
4) Нет версии с LAPACK.

**Comment by Vopreky** [comment]
Я не придумал метода для использования блоков без рекурсии

Фортран сейчас попробую переделать.

Я согласен с тем, что blas по сути не используется, но я не знаю, куда его применить, все элементы матриц L U вычисляются просто по формулам с лекций численных методов линейной алгебры.

**Comment by dzheltkov** [comment]
Всё довольно просто (и я рассказывал это на семинаре):
рассматриваете матрицу как блочную 2 x 2 с блоками A_{11}, A_{12}, A_{21}, A_{22}, где блок A_{11} -- квадратный со сторонами равными b, где b -- параметр размера блока.
Можно показать, что в разложении A = LU, если мы рассмотрим L и U как 2x2 блочные матрицы соответствующих размеров, то A_{11} = L_{11} U_{11}, то есть LU-разложение матрицы A _{11} позволяет нам найти эти блоки.
также легко понять, что L_{21} = A_{21} U_{11}^{-1}, а U_{12} = L_{11}^{-1} A_{12} (то есть эти два блока находятся если найдено LU-разложение для A_{11}, кроме того, чтобы их найти можно использовать функцию BLAS, которая реализует решение треугольной системы), а блоки L_{22} и U_{22} находятся как LU-разложение матрицы A_{22} - L_{21} U_{12} (эту матрицу тоже можно найти с помощью умножения матриц из BLAS).
Далее можно применять в цикле (или рекурсивно, конечно, просто рекурсия более понятная, чем у вас, но я бы использовал цикл, так как с ним ещё понятнее и проще).

**Comment by Vopreky** [comment]
Я сделал программу с использованием blas lapack, но я в итоге оттуда использовал не решение системы, а перемножение матриц, к которому я смог найти нужные константы. 

В фортране я смог воспользоваться решением системы и сделал правильную индексацию.

Завтра(сегодня) я еще постараюсь добавить проверку в фортран и, если что-то ещё скажете переделывать, тоже сделаю.

**Comment by dzheltkov** [comment]
Во-первых, найти описание функций, где описаны все необходимые константы, не так уж сложно, например:
https://www.ibm.com/docs/en/essl/6.2?topic=mos-strsm-dtrsm-ctrsm-ztrsm-solution-triangular-systems-equations-multiple-right-hand-sides

Во-вторых, блочная версия у вас всё ещё принципиально неправильно сделана. То есть, блочная версия делается для того, чтобы произвести кэш-оптимизации, то есть размер блока b (то есть порядок блока A_{11}) выбирается так, чтобы что-то (в данной случае -- блок A_{11}) помещалось в кэш.
При этом физически матрицу на блоки, естественно, разбивать не нужно, её только рассматривают как блочную.
А у вас просто разбивается на четыре матрицы одинаковых размеров (точнее, даже не разбивается, а физически задаётся как 4 матрицы) и делается два шага.

В-третьих в коде куча лишних копирований матриц (но это меньшая из проблем).

В-четвёртых, не отчёта со временами работы различных версий алгоритма.
